version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
init:
  # To avoid duplicated executables in PATH, see https://github.com/ruby/spec/pull/468
  - set PATH=C:\Ruby%ruby_version%\bin;C:\msys64\usr\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows

install:
  - ruby --version
  - git --version
build_script:
  - bundle update
  - bundle install
test_script:
  - git config --global user.email "server@0pdd.com"
  - git config --global user.name "0pdd.com"
  - rake
cache:
  - C:\Ruby200\bin -> pdd.gemspec
  - C:\Ruby200\lib\ruby\gems\2.0.0 -> pdd.gemspec
environment:
  matrix:
    - ruby_version: 26-x64
    - ruby_version: 26
